name: Docker Hub Publication
on: [push]
jobs:
  Publish-Docker-Images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository sources
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: 1.14.4/x86_64-bionic
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
          push: true
          tags: dogecoin/dogecoin:1.14.4
